name: Synchro Carte Wurm Legion Hosting

on:
  schedule:
    - cron: '0 4 * * *' # S'exécute automatiquement toutes les nuits à 4h du matin
  workflow_dispatch:      # Ajoute un bouton sur GitHub pour lancer la mise à jour en 1 clic

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Connexion au dépôt GitHub
      uses: actions/checkout@v4

    - name: Télécharger la carte depuis le SFTP Legion Hosting
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.LEGION_HOST_IP }}
        username: ${{ secrets.LEGION_FTP_USER }}
        password: ${{ secrets.LEGION_FTP_PASSWORD }}
        port: 22 # Port standard sécurisé pour le SFTP
        local-dir: ./map-folder/
        server-dir: /wurm/mapvieweroutput/ # ⚠️ REMPLACEZ PAR VOTRE DOSSIER CHEZ LEGION SI BESOIN
        method: download
        dangerous-clean-local: false

    - name: Mettre la carte en ligne sur GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: ./map-folder/
        branch: gh-pages # Crée le site internet pour vos joueurs

